---
- name: Include user tasks
  when: lb2958_bastion_addon_user_config | bool
  ansible.builtin.include_tasks:
    file: users.yml
  loop: "{{ lb2958_bastion_addon_hosts }}"
  loop_control:
    loop_var: _hostname_

- name: Include lb2958 package addition task
  when: lb2958_bastion_addon_package | bool
  ansible.builtin.include_tasks:
    file: package-add.yml
  loop: "{{ lb2958_bastion_addon_hosts }}"
  loop_control:
    loop_var: _hostname_

- name: Include lb2958 subscription task
  when: lb2958_bastion_addon_subscription | bool
  ansible.builtin.include_tasks:
    file: subscribe-rhc.yml
  loop: "{{ lb2958_bastion_addon_hosts }}"
  loop_control:
    loop_var: _hostname_

- name: Save node1 info
  agnosticd_user_info:
    data:
      node1_public_hostname: "node1.{{ guid}}{{subdomain_base_suffix}}"
      node1_username: "{{ lb2958_bastion_addon_username }}"
      node1_password: "{{ lb2958_bastion_addon_user_password }}"
  when: lb2958_bastion_addon_agnosticd_user_info | bool   