---
- name: Become block
  become: true
  block:
    - name: Set Ansible Python interpreter to k8s virtualenv
      ansible.builtin.set_fact:
        ansible_python_interpreter: /usr/libexec/platform-python
  
    - name: Install tcsh and Red Hat Lightspeed assistant
      ansible.builtin.command: >-
        dnf install -y tcsh
      register: install_tcsh
      failed_when: install_tcsh.rc != 0
      delegate_to: "{{ _hostname_ }}"

    - name: Enable copr repository
      ansible.builtin.command: >-
        dnf copr enable -y @rhel-lightspeed/command-line-assistant
      register: enable_copr
      failed_when: enable_copr.rc != 0
      delegate_to: "{{ _hostname_ }}"

    - name: Install command-line-assistant
      ansible.builtin.command: >-
        dnf install -y command-line-assistant
      register: install_cla
      failed_when: install_cla.rc != 0
      delegate_to: "{{ _hostname_ }}"

    - name: Set Ansible Python interpreter to k8s virtualenv
      ansible.builtin.set_fact:
        ansible_python_interpreter: /opt/virtualenvs/k8s/bin/python        