---
- name: Become block
  become: true
  block:
    - name: Set Ansible Python interpreter to k8s virtualenv
      ansible.builtin.set_fact:
        ansible_python_interpreter: /usr/libexec/platform-python
  
    - name: Unregister From Subscription Manager
      ansible.builtin.command: subscription-manager unregister
      register: r_unregister
      failed_when: >-
        r_unregister is failed and
        r_unregister.stderr | default('') != 'This system is currently not registered.'
      ignore_errors: true
      delegate_to: "{{ _hostname_ }}"

    - name: Remove satellite Cert
      ansible.builtin.package:
        name: katello-ca-consumer-*.noarch
        state: absent
        disablerepo: "*"
      ignore_errors: true
      delegate_to: "{{ _hostname_ }}"

    - name: Update CA Trust Bundle
      ansible.builtin.command: update-ca-trust
      delegate_to: "{{ _hostname_ }}"

    - name: Find current repository files
      ansible.builtin.find:
        paths: /etc/yum.repos.d
        recurse: no
        patterns:
        - '*.repo'
      register: r_find_repos
      delegate_to: "{{ _hostname_ }}"

    - name: Remove current repository files
      ansible.builtin.file:
        path: "{{ file.path }}"
        state: absent
      loop: "{{ r_find_repos.files }}"
      loop_control:
        loop_var: file
        label: "{{ file.path }}"
      delegate_to: "{{ _hostname_ }}"

    - name: Restore rhsm.conf
      ansible.builtin.copy:
        src: /etc/rhsm/rhsm.conf.cloud_save
        dest: /etc/rhsm/rhsm.conf
        remote_src: true
        mode: "0644"
      delegate_to: "{{ _hostname_ }}"

    - name: Register node with Red Hat Insights / RHC
      ansible.builtin.command: >-
        rhc connect
        -o {{ lb2958_bastion_addon_org }}
        -a {{ lb2958_bastion_addon_activation_key }}
      ignore_errors: true        
      delegate_to: "{{ _hostname_ }}"

    - name: Set Ansible Python interpreter to k8s virtualenv
      ansible.builtin.set_fact:
        ansible_python_interpreter: /opt/virtualenvs/k8s/bin/python     